### ISSUE TITLE
erro in reconstruct_contig.py when testing

### ISSUE THREAD

**Issue by zhuyiqin** [Magdoll/Cogent#14]
Hi, Dear
I met a problem when running the test using command "reconstruct_contig.py test_human/test_human_0" as follows:
/SDIVF/GUEST/zhuyb/Software/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Bio/Seq.py:349: BiopythonDeprecationWarning: This method is obsolete; please use str(my_seq) instead of my_seq.tostring().
  BiopythonDeprecationWarning)
Opening file cogent.fa
  Processed short contigs (<1000000 nt): ...
============================================================
Contig mapping information has been written to file cogent.coords.
You should look at this file, and edit it if necessary
If everything is okay, you should proceed by running
    make gmapdb
============================================================
Reading coordinates from file cogent.coords
Logging contig path0 at path0:1..5342 in genome cogent
Logging contig path1 at path1:1..5312 in genome cogent
Logging contig path2 at path2:1..5286 in genome cogent
Chromosome path0 has universal coordinates 1..5342
Chromosome path1 has universal coordinates 5343..10654
Chromosome path2 has universal coordinates 10655..15940
Writing IIT file header information...done
Processing null division/chromosome...sorting...writing...done (3 intervals)
Writing IIT file footer information...done
Writing IIT file header information...done
Processing null division/chromosome...sorting...writing...done (3 intervals)
Writing IIT file footer information...done
Genome length is 15940 nt
Trying to allocate 1497*4 bytes of memory...succeeded.  Building genome in memory.
Reading coordinates from file cogent.coords
Writing contig path0 to universal coordinates 1..5342 in genome cogent
Writing contig path1 to universal coordinates 5343..10654 in genome cogent
Writing contig path2 to universal coordinates 10655..15940 in genome cogent
A total of 0 non-ACGTNX characters were seen in the genome.
Indexing offsets of oligomers in genome cogent (every 3 bp), position 0
Writing 16777217 offsets to file with total of 5303 positions
Trying to allocate 5303*4 bytes of memory...succeeded.  Building positions in memory.
Indexing positions of oligomers in genome cogent (every 3 bp), position 0
Writing 5303 genomic positions to file ./cogent.ref3positions ...
Copying files to directory ./cogent
GMAP version 2011-03-28.v3 called with args: -D . -d cogent -n 100 -f gff3_gene -t 1 in.trimmed.fa
Note: >1 sequence detected, so index files are being memory mapped.
  GMAP can run slowly at first while the computer starts to accumulate
  pages from the hard disk into its cache.  To copy index files into RAM
  instead of memory mapping, use -B 3 or -B 4, if you have enough RAM.
  For more speed, also try multiple threads (-t <int>), if you have multiple processors or cores.
Allocating memory for ref3 offsets db...done (67108868 bytes, 0.03 sec)
Pre-loading ref3 positions db....done (21212 bytes, 6 pages, 0.00 sec)
Pre-loading compressed genome....done (5988 bytes, 2 pages, 0.00 sec)
Processed 10 queries in 0.38 seconds (26.32 queries/sec)
Traceback (most recent call last):
  File "/SDIVF/GUEST/zhuyb/Software/anaconda3/envs/anaCogent/bin/reconstruct_contig.py", line 4, in <module>
    __import__('pkg_resources').run_script('Cogent==2.1', 'reconstruct_contig.py')
  File "/SDIVF/GUEST/zhuyb/Software/anaconda3/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/SDIVF/GUEST/zhuyb/Software/anaconda3/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/SDIVF/GUEST/zhuyb/Software/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 352, in <module>
    main()
  File "/SDIVF/GUEST/zhuyb/Software/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 265, in main
    run_Cogent_on_input()
  File "/SDIVF/GUEST/zhuyb/Software/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 245, in run_Cogent_on_input
    post_gmap_processing(seqrecs=seqrecs)
  File "/SDIVF/GUEST/zhuyb/Software/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/Cogent/Utils.py", line 39, in post_gmap_processing
    for r in reader:
  File "/SDIVF/GUEST/zhuyb/Software/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/Cogent/GFF.py", line 377, in next
    return self.read()            
  File "/SDIVF/GUEST/zhuyb/Software/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/Cogent/GFF.py", line 413, in read
    rec = gmapRecord(chr, coverage, identity, strand, seqid)
UnboundLocalError: local variable 'coverage' referenced before assignment

Could you please tell me how to solve it? Thanks.

**Comment by Magdoll** [comment]
Hi,
It looks like an issue with processing GMAP. It appears you are using an extremely old version of GMAP (`GMAP version 2011-03-28.v3 `) which was never tested. Please try upgrading to a newer version of GMAP (preferably the latest, if not after 2016) and let me know if you still see issues.

FYI, I will be on vacation until 11/30. Expect delay in responses.

--Liz

**Comment by zhuyiqin** [comment]
Thanks, it works well after updating the GMAP.
