### ISSUE TITLE
error in reconstruct_contig.py

### ISSUE THREAD

**Issue by zhuyiqin** [Magdoll/Cogent#15]
Hi,

Some jobs failed when I ran reconstruct_contig.py with the following messages:
Traceback (most recent call last):
  File "/zfssz4/BC_COM_P4/F15HTSSCKF3698/soft/anaconda3/envs/anaCogent/bin/reconstruct_contig.py", line 4, in <module>
    __import__('pkg_resources').run_script('Cogent==2.1', 'reconstruct_contig.py')
  File "/zfssz4/BC_COM_P4/F15HTSSCKF3698/soft/anaconda3/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/zfssz4/BC_COM_P4/F15HTSSCKF3698/soft/anaconda3/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/zfssz4/BC_COM_P4/F15HTSSCKF3698/soft/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 352, in <module>
    main()
  File "/zfssz4/BC_COM_P4/F15HTSSCKF3698/soft/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 265, in main
    run_Cogent_on_input()
  File "/zfssz4/BC_COM_P4/F15HTSSCKF3698/soft/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 245, in run_Cogent_on_input
    post_gmap_processing(seqrecs=seqrecs)
  File "/zfssz4/BC_COM_P4/F15HTSSCKF3698/soft/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/Cogent/Utils.py", line 39, in post_gmap_processing
    for r in reader:
  File "/zfssz4/BC_COM_P4/F15HTSSCKF3698/soft/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/Cogent/GFF.py", line 377, in next
    return self.read()            
  File "/zfssz4/BC_COM_P4/F15HTSSCKF3698/soft/anaconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-2.1-py2.7.egg/Cogent/GFF.py", line 448, in read
    cds_exons.append(Interval(rstart1-1, rend1))
  File "intersection.pyx", line 290, in bx.intervals.intersection.Interval.__init__ (lib/bx/intervals/intersection.c:3752)
OverflowError: value too large to convert to int

I have no idea what the error means? My input data only has 9 sequences.
Thank you.

**Comment by Magdoll** [comment]
@zhuyiqin ,

This is an unusual error. The `bx.intervals` package seems to be complaining that the genomic interval given is too large!? 

Would it be possible to share the input sequence with me? You can email it to etseng@pacb.com.

--Liz

**Comment by zhuyiqin** [comment]
@Magdoll ,

There are more than 20 thousand identified families for my data, about 2 thousand of them have this issue. I have sent one of the problematic input sequences to your email.
Thank you.
