### ISSUE TITLE
there was no run_preCluster.py script

### ISSUE THREAD

**Issue by kaihuang2016** [Magdoll/Cogent#19]
Hi @Magdoll ,
I was installed Cogent using Anaconda almost follow the manuals, only in "conda install -c http://conda.anaconda.org/timcera pulp" cannot find user timcera, so I run "conda install -c http://conda.anaconda.org/conda-forge pulp", and there was no error in the installing. In the end, run_mash.py and other scripts are in the path of Anaconda2-5.0.1/envs/anaCogent/bin/, but there was no run_preCluster.py script. Was there some mistakes in my installing? And run "run_mash.py --version", the error is:
Traceback (most recent call last):
  File "/data/software/Anaconda/Anaconda2-5.0.1/envs/anaCogent/bin/run_mash.py", line 4, in <module>
    __import__('pkg_resources').run_script('Cogent==2.1', 'run_mash.py')
  File "/data/software/Anaconda/Anaconda2-5.0.1/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data/software/Anaconda/Anaconda2-5.0.1/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1518, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/run_mash.py' not found in metadata at '/data/software/Cogent/Cogent-v2.1/Cogent.egg-info'

**Comment by kaihuang2016** [comment]
Hi @Magdoll ,
I have finded the closed issues to reinstalled Cogent with run "conda install -c agerlach pulp". And find this script in cDNA_Cupcake. My mistake. Thanks.
