### ISSUE TITLE
libssw.so: undefined symbol: cigar_int_to_len

### ISSUE THREAD

**Issue by zhyw86** [Magdoll/Cogent#20]
I was have an issue your answer before about ssw_wrap.py. To solve the problem, I copied the ssw_wrap.py from this repo: https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library

Now I am getting: libssw.so: undefined symbol: cigar_int_to_len.

When I get back to the code, I found this function is in  ssw_cpp.cpp. Why this function is not included in the lib file?

**Comment by Magdoll** [comment]
Hi,
You should not have to directly copy `ssw_wrap.py` from other repos! It is already included in the Cogent installation.

Please make sure you have installed Cogent per [installation wiki here](https://github.com/Magdoll/Cogent/wiki/Installing-Cogent) and that you have the appropriate variables configured:

```
export PATH=$HOME/anaconda2/bin:$PATH
source activate anaCogent
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<your_dir>/Cogent/Complete-Striped-Smith-Waterman-Library/src
export PYTHONPATH=$PYTHONPATH:<your_dir>/Cogent/Complete-Striped-Smith-Waterman-Library/src
```

**Comment by zhyw86** [comment]
I forgot to use python install.

Thanks!

**Comment by Zunaick** [comment]
Hi, I am also facing the similar issue. I installed Complete-Striped-Smith-Waterman-Library from the link in the tutorial (https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library). 
But after installion when i executed run_mash.py it gave following error:

Traceback (most recent call last):
  File "/home/user/anaconda2/bin/run_mash.py", line 4, in <module>
    __import__('pkg_resources').run_script('Cogent==3.6', 'run_mash.py')
  File "/home/user/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/user/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/nfsroot/home/user/anaconda2/lib/python2.7/site-packages/Cogent-3.6-py2.7.egg/EGG-INFO/scripts/run_mash.py", line 6, in <module>
    from Cogent.sanity_checks import sanity_check_mash_exists
  File "/nfsroot/home/user/anaconda2/lib/python2.7/site-packages/Cogent-3.6-py2.7.egg/Cogent/sanity_checks.py", line 3, in <module>
    from Cogent import splice_align
  File "/nfsroot/home/user/anaconda2/lib/python2.7/site-packages/Cogent-3.6-py2.7.egg/Cogent/splice_align.py", line 4, in <module>
    from ssw_wrap import Aligner
**ImportError: No module named ssw_wrap**

So i copied the ssw_wrap.py and copied it and did python ssw_wrap.py install. But it gave following error.

Traceback (most recent call last):
  File "/home/user/anaconda2/bin/run_mash.py", line 4, in <module>
    __import__('pkg_resources').run_script('Cogent==3.6', 'run_mash.py')
  File "/home/user/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/user/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/nfsroot/home/user/anaconda2/lib/python2.7/site-packages/Cogent-3.6-py2.7.egg/EGG-INFO/scripts/run_mash.py", line 6, in <module>
    from Cogent.sanity_checks import sanity_check_mash_exists
  File "/nfsroot/home/user/anaconda2/lib/python2.7/site-packages/Cogent-3.6-py2.7.egg/Cogent/sanity_checks.py", line 3, in <module>
    from Cogent import splice_align
  File "/nfsroot/home/user/anaconda2/lib/python2.7/site-packages/Cogent-3.6-py2.7.egg/Cogent/splice_align.py", line 4, in <module>
    from ssw_wrap import Aligner
  File "/home/user/2018/tools/Complete-Striped-Smith-Waterman-Library-master/src/ssw_wrap.py", line 267, in <module>
    class PyAlignRes(object):
  File "/home/user/2018/tools/Complete-Striped-Smith-Waterman-Library-master/src/ssw_wrap.py", line 282, in PyAlignRes
    cigar_int_to_len = libssw.cigar_int_to_len
  File "/home/user/anaconda2/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/home/user/anaconda2/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
**Complete-Striped-Smith-Waterman-Library-master/src/libssw.so: undefined symbol: cigar_int_to_len**

Please help me proceeding.

Thank you

**Comment by zhyw86** [comment]
Did you use pip to install the cogent?
That helped me to solve the problem. But I did not use anaconda, you may want to try conda install?

**Comment by Zunaick** [comment]
Hi, thanks for response. Setting path for the script installed solved my problem.
