### ISSUE TITLE
TypeError: 'dictionary-keyiterator' in reconstruct_contig.py

### ISSUE THREAD

**Issue by lijl459** [Magdoll/Cogent#25]
Hellow,
  Some jobs failed when I was Testing Cogent with the following messages:
  python /home/share/user/user150/software/Cogent/Cogent/Cogent/reconstruct_contig.py test_human/test_human_0
2.10-r763-dirty
/home/share/user/user150/software/Cogent/anaconda2/pkgs/Bio/Seq.py:349: BiopythonDeprecationWarning: This method is obsolete; please use str(my_seq) instead of my_seq.tostring().
  BiopythonDeprecationWarning)
Traceback (most recent call last):
  File "/home/share/user/user150/software/Cogent/Cogent/Cogent/reconstruct_contig.py", line 337, in <module>
    main()
  File "/home/share/user/user150/software/Cogent/Cogent/Cogent/reconstruct_contig.py", line 259, in main
    run_Cogent_on_input()
  File "/home/share/user/user150/software/Cogent/Cogent/Cogent/reconstruct_contig.py", line 181, in run_Cogent_on_input
    sp.reachability(G, mermap, visited, path_d)
  File "/home/share/user/user150/software/Cogent/Cogent/Cogent/splice_graph.py", line 286, in reachability
    reachability_helper(G, source, [], visited, mermap, path_d)
  File "/home/share/user/user150/software/Cogent/Cogent/Cogent/splice_graph.py", line 320, in reachability_helper
    reachability_helper(G, G.successors(cur).next(), [cur], visited, mermap, path_d)
  File "/home/share/user/user150/software/Cogent/Cogent/Cogent/splice_graph.py", line 314, in reachability_helper
    reachability_helper(G, G.successors(cur).next(), chain + [cur], visited, mermap, path_d)
  File "/home/share/user/user150/software/Cogent/Cogent/Cogent/splice_graph.py", line 318, in reachability_helper
    collapse_chain(G, chain+[cur], mermap, path_d)
  File "/home/share/user/user150/software/Cogent/Cogent/Cogent/splice_graph.py", line 229, in collapse_chain
    sanity_check_is_chain(G, chain)
  File "/home/share/user/user150/software/Cogent/Cogent/Cogent/sanity_checks.py", line 66, in sanity_check_is_chain
    print G.predecessors(n1)[0]
TypeError: 'dictionary-keyiterator' object has no attribute '__getitem__'

I don't know how to solve this problem. My Python version is 2.7.14 and I used the command like "python reconstruct_contig.py test_human/test_human_0"
Thank you very much!

**Comment by Magdoll** [comment]
Hi @lijl459 ,

Can you confirm the networkx version you have? It looks like a package version issue. Cogent is currently tested with version 1.10.

```
>>> import networkx
>>> networkx.__version__
`1.10`
```

Depending on your version, you may need to [upgrade or downgrade your networkx in Anaconda](https://stackoverflow.com/questions/23974217/how-do-i-revert-to-a-previous-package-in-anaconda).

**Comment by abeyeu** [comment]
@Magdoll
I am carrying on a population genetics work. 
Data: high-quality full-length transcriptome sequences of one sample and NGS transcriptome of many samples (PE150). 
I would use spliced aligners (STAR ) map NGS data to cogent2.fa and then follow GATK protocol to call variants in NGS data. Is it makes sense?
Thanks very much 
zhu
