### ISSUE TITLE
KeyError: 'weight' in reconstructing contig

### ISSUE THREAD

**Issue by fantastycrane** [Magdoll/Cogent#33]
Hi @Magdoll ,

Multiple key errors occurred in different gene family while reconstructing contig. Here is an example of details about these errors.

"""
Traceback (most recent call last):
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/bin/reconstruct_contig.py", line 4, in <module>
    __import__('pkg_resources').run_script('Cogent==3.3', 'reconstruct_contig.py')
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 337, in <module>
    main()
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 259, in main
    run_Cogent_on_input()
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 220, in run_Cogent_on_input
    sp.reachability(G, mermap, {}, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 294, in reachability
    reachability_helper(G, source, [], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 328, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 320, in reachability_helper
    reachability_helper(G, n, [], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 322, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), chain + [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 328, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 328, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 320, in reachability_helper
    reachability_helper(G, n, [], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 322, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), chain + [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 328, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 320, in reachability_helper
    reachability_helper(G, n, [], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 322, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), chain + [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 328, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 320, in reachability_helper
    reachability_helper(G, n, [], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 322, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), chain + [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 320, in reachability_helper
    reachability_helper(G, n, [], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 322, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), chain + [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 328, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 328, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 320, in reachability_helper
    reachability_helper(G, n, [], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 322, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), chain + [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 328, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 320, in reachability_helper
    reachability_helper(G, n, [], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 322, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), chain + [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 320, in reachability_helper
    reachability_helper(G, n, [], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 322, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), chain + [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 328, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 320, in reachability_helper
    reachability_helper(G, n, [], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 322, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), chain + [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 328, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 320, in reachability_helper
    reachability_helper(G, n, [], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 322, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), chain + [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 328, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 322, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), chain + [cur], visited, mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 317, in reachability_helper
    collapse_chain(G, chain+[cur], mermap, path_d)
  File "/share/nas1/yangch/bin/anaconda/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.3-py2.7.egg/Cogent/splice_graph.py", line 245, in collapse_chain
    weights_in_path.append(G.get_edge_data(chain[i], chain[i+1])['weight'])
KeyError: 'weight'
"""

I suspected that get_edge_data function in networkx module returned a none subject. But I was not able to confirm or exam exact reasons.  Could you help take a look? Thanks.

**Comment by Magdoll** [comment]
hi @fantastycrane ,

I've sent a file upload request to your email (fantastycrane@163.com). Looks like it may be that the "weight" attribute was not properly propagated in the alg. I'll take a look.

Thanks,
--Liz

**Comment by fantastycrane** [comment]
Files have been uploaded. Please Check. Thanks.

**Comment by Magdoll** [comment]
Hi @fantastycrane ,

Cogent v3.5 should have this problem fixed. Please confirm.

--Liz

**Comment by fantastycrane** [comment]
Thanks. I'll upgrade Cogent and see how it goes.

**Comment by fantastycrane** [comment]
Hi @Magdoll ,

The key error issue has been solved. Only reconstruction in specific gene family seems to be running forever.  It keeps outputting following info in hello.log.

"""
2018-05-24 09:37:33,813 - Cogent - INFO - CYCLE detected through path analysis! Raise CycleDetectedException!
2018-05-24 09:37:33,822 - Cogent - INFO - Trying to raise k=120. Rerun attempt.
2018-05-24 09:37:35,260 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: 3429 in-seq cycle found with max common         sequence analysis showing min: 121, max: 590, mean: 249.778652668
2018-05-24 09:37:35,268 - Cogent - INFO - Adjusting k-mer size to: 100
2018-05-24 09:37:38,125 - Cogent - INFO - CYCLE detected through path analysis! Raise CycleDetectedException!
2018-05-24 09:37:38,137 - Cogent - INFO - Trying to raise k=120. Rerun attempt.
2018-05-24 09:37:39,584 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: 3429 in-seq cycle found with max common         sequence analysis showing min: 121, max: 590, mean: 249.778652668
2018-05-24 09:37:39,591 - Cogent - INFO - Adjusting k-mer size to: 100
2018-05-24 09:37:42,384 - Cogent - INFO - CYCLE detected through path analysis! Raise CycleDetectedException!
2018-05-24 09:37:42,395 - Cogent - INFO - Trying to raise k=120. Rerun attempt.
2018-05-24 09:37:43,876 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: 3429 in-seq cycle found with max common         sequence analysis showing min: 121, max: 590, mean: 249.778652668
2018-05-24 09:37:43,883 - Cogent - INFO - Adjusting k-mer size to: 100
2018-05-24 09:37:46,740 - Cogent - INFO - CYCLE detected through path analysis! Raise CycleDetectedException!
2018-05-24 09:37:46,750 - Cogent - INFO - Trying to raise k=120. Rerun attempt.
2018-05-24 09:37:48,119 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: 3429 in-seq cycle found with max common         sequence analysis showing min: 121, max: 590, mean: 249.778652668
2018-05-24 09:37:48,127 - Cogent - INFO - Adjusting k-mer size to: 100
2018-05-24 09:37:50,895 - Cogent - INFO - CYCLE detected through path analysis! Raise CycleDetectedException!
2018-05-24 09:37:50,906 - Cogent - INFO - Trying to raise k=120. Rerun attempt.
2018-05-24 09:37:52,253 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: 3429 in-seq cycle found with max common         sequence analysis showing min: 121, max: 590, mean: 249.778652668
2018-05-24 09:37:52,263 - Cogent - INFO - Adjusting k-mer size to: 100
2018-05-24 09:37:55,062 - Cogent - INFO - CYCLE detected through path analysis! Raise CycleDetectedException!
2018-05-24 09:37:55,072 - Cogent - INFO - Trying to raise k=120. Rerun attempt.
2018-05-24 09:37:56,426 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: 3429 in-seq cycle found with max common         sequence analysis showing min: 121, max: 590, mean: 249.778652668
2018-05-24 09:37:56,435 - Cogent - INFO - Adjusting k-mer size to: 100
2018-05-24 09:37:59,170 - Cogent - INFO - CYCLE detected through path analysis! Raise CycleDetectedException!
2018-05-24 09:37:59,182 - Cogent - INFO - Trying to raise k=120. Rerun attempt.
2018-05-24 09:38:00,622 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: 3429 in-seq cycle found with max common         sequence analysis showing min: 121, max: 590, mean: 249.778652668
2018-05-24 09:38:00,629 - Cogent - INFO - Adjusting k-mer size to: 100
2018-05-24 09:38:03,448 - Cogent - INFO - CYCLE detected through path analysis! Raise CycleDetectedException!
2018-05-24 09:38:03,459 - Cogent - INFO - Trying to raise k=120. Rerun attempt.
2018-05-24 09:38:04,974 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: 3429 in-seq cycle found with max common         sequence analysis showing min: 121, max: 590, mean: 249.778652668
2018-05-24 09:38:04,983 - Cogent - INFO - Adjusting k-mer size to: 100
"""

**Comment by Magdoll** [comment]
Hi @fantastycrane ,
I must have written a loop somewhere. Would you mind sharing the file? Hopefully this time I get rid of the error once and for all.

--Liz

**Comment by fantastycrane** [comment]
Hi @Magdoll ,
The requested files have been uploaded. Please check.

**Comment by Magdoll** [comment]
Hi @fantastycrane ,
FIles have been received. I'll keep you updated.

**Comment by fantastycrane** [comment]
Any progress on this issue?

**Comment by Magdoll** [comment]
I’m currenrly traveling until 6/18. May have to wait till get back. Sorry

**Comment by Magdoll** [comment]
@fantastycrane ,
The file you sent successfully completed through Cogent v3.5. I've dropped off the results back to your email. Please let me know when you've picked it up.
--Liz

**Comment by fantastycrane** [comment]
@Magdoll ,
I updated Cogent to v3.6 and tested it on the failed case. It worked fine. Thanks.
