### ISSUE TITLE
AssertionError message when running reconstruct_contig.py (cogent 3.5)

### ISSUE THREAD

**Issue by jayceejiao** [Magdoll/Cogent#46]
Hi @Magdoll,

I am using Cogent 3.5 to process the high-quality isoforms generated from the isoseq3 pipeline. Now I still have one failed job in the reconstruction step. Below is the error message I got:

> 2.10-r770-dirty
> /data/jiaochen/miniconda3/envs/anaCogent/lib/python2.7/site-packages/Bio/Seq.py:349: BiopythonDeprecationWarning: This method is obsolete; please use str(my_seq) instead of my_seq.tostring().
>   BiopythonDeprecationWarning)
> 
> 
> 
> 
> 
> 
> [M::mm_idx_gen::0.001*5.07] collected minimizers
> [M::mm_idx_gen::0.001*3.33] sorted minimizers
> [M::main::0.001*3.25] loaded/built the index for 1 target sequence(s)
> [M::mm_mapopt_update::0.001*3.09] mid_occ = 2
> [M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 1
> [M::mm_idx_stat::0.001*2.92] distinct minimizers: 40 (100.00% are singletons); average occurrences: 1.000; average spacing: 3.325
> [M::worker_pipeline::0.005*0.97] mapped 6 sequences
> [M::main] Version: 2.10-r770-dirty
> [M::main] CMD: minimap2 -ax splice -t 1 cogent.fa in.trimmed.fa
> [M::main] Real time: 0.005 sec; CPU: 0.005 sec
> Traceback (most recent call last):
>   File "/home/jiaochen/miniconda3/envs/anaCogent/bin/reconstruct_contig.py", line 4, in <module>
>     __import__('pkg_resources').run_script('Cogent==3.5', 'reconstruct_contig.py')
>   File "/home/jiaochen/miniconda3/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/home/jiaochen/miniconda3/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
>     exec(code, namespace, namespace)
>   File "/data/jiaochen/miniconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.5-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 337, in <module>
>     main()
>   File "/data/jiaochen/miniconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.5-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 259, in main
>     run_Cogent_on_input()
>   File "/data/jiaochen/miniconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.5-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 239, in run_Cogent_on_input
>     post_minimap2_processing('cogent.fa', sam_file, 'cogent2', seqrecs=seqrecs)
>   File "/data/jiaochen/miniconda3/envs/anaCogent/lib/python2.7/site-packages/Cogent-3.5-py2.7.egg/Cogent/Utils.py", line 48, in post_minimap2_processing
>     assert r.sID.startswith('path')  # chr should be path0, path1, etc
> AssertionError

Do you know why I got this message and how to deal with this? I can send you the in.fa and in.weights files. Thanks!

Chen

**Comment by Magdoll** [comment]
Hi,
Indeed, from the error it's not obvious to me what went wrong.

Please give me an email to request a file upload to. 

--Liz

**Comment by steffi778** [comment]
Hey,
I got exactly the same error for 4 of my reconstructions (Cogent 3.5). In the hello.log file of the respective files you can find the following:

2018-09-05 09:23:26,592 - Cogent - INFO - Setting k-mer size to: 60
2018-09-05 09:23:26,592 - Cogent - INFO - Setting expected error rate to: 1%
2018-09-05 09:23:26,625 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: None found at k=60
2018-09-05 09:23:26,718 - Cogent - INFO - Doing nx.cycle_detection....
2018-09-05 09:23:26,720 - Cogent - INFO - Initial Graph Size: 4 nodes, 2 edges
2018-09-05 09:23:26,721 - Cogent - INFO - Post-Reduction Graph Size: 2 nodes, 0 edges
2018-09-05 09:23:26,722 - Cogent.process_path - INFO - number of paths now: 1
2018-09-05 09:23:26,722 - Cogent.process_path - INFO - number of paths now: 1
2018-09-05 09:23:26,722 - Cogent.process_path - INFO - number of paths now: 1
2018-09-05 09:23:26,722 - Cogent.process_path - INFO - number of paths now: 2

if I increase k to 200 the hello.log file shows the following:
2018-09-05 09:24:46,582 - Cogent - INFO - Setting k-mer size to: 200
2018-09-05 09:24:46,582 - Cogent - INFO - Setting expected error rate to: 1%
2018-09-05 09:24:46,630 - Cogent.splice_cycle - INFO - K-mer in-seq cycle detection: None found at k=200
2018-09-05 09:24:46,761 - Cogent - INFO - Doing nx.cycle_detection....
2018-09-05 09:24:46,764 - Cogent - INFO - Initial Graph Size: 2 nodes, 1 edges
2018-09-05 09:24:46,766 - Cogent - INFO - Post-Reduction Graph Size: 1 nodes, 0 edges
2018-09-05 09:24:46,766 - Cogent.process_path - INFO - number of paths now: 1
2018-09-05 09:24:46,766 - Cogent.process_path - WARNING - [BUG] Missing good_for for transcript/10742. Maybe known issue (graph cycles). Use own path.
2018-09-05 09:24:46,766 - Cogent.process_path - WARNING - [BUG] Missing good_for for transcript/10879. Maybe known issue (graph cycles). Use own path.

Maybe it will help you to find the bug?

Thanks,
Stephie

**Comment by jayceejiao** [comment]
Hi Liz,

my email address is cj334@cornell.edu. Thanks!

Chen

**Comment by Magdoll** [comment]
@jayceejiao , a request email has been sent to you to upload the file.

@steffi778 , let me see what happens with @jayceejiao's error. Maybe I can figure out why this happens in general.

**Comment by jayceejiao** [comment]
Hi @Magdoll ,

I have another project also reports this error for three families. And I found there is an unmapped sequence in in.trimmed.fa.sam. Then I just deleted this sequence in in.fa and in.weights and then I can finish the pipeline.   Thanks for your help!

Chen

**Comment by Magdoll** [comment]
HI @jayceejiao ,

I just ran your `in.fa` (the one with the IDs below) on Cogent v3.6. and it completed without issue, by the way. I didn't modify any of your input.

```
>transcript/51811
>transcript/51860
>transcript/51697
>transcript/51836
>transcript/51842
>transcript/51822
```

**Comment by Magdoll** [comment]
@steffi778 ,

If you are still experiencing problems after upgrading to Cogent v3.6, please let me know. Otherwise I'm closing this case.

**Comment by steffi778** [comment]
Hey @Magdoll 

Thank you very much for your help! But where can I find version 3.6? When I try to install it via git and conda, the newest version I can get is still 3.5

**Comment by Magdoll** [comment]
@steffi778 ,

The `README.md` showed the wrong version (which I just fixed), but `setup.py` correctly showed 3.6. Please update and try.
--Liz
