### ISSUE TITLE
reconstruct_contig.py: Incompatible with python version 2.7.15

### ISSUE THREAD

**Issue by AxelMacFoly** [Magdoll/Cogent#63]
Hi Magdoll,
with python version 2.7.15 the reconstruct_contig.py script throws an AttributeError:

`Traceback (most recent call last):
  File "/home/mpimp-golm.mpg.de/afischer/.conda/envs/anaCogent2/bin/reconstruct_contig.py", line 4, in <module>
    __import__('pkg_resources').run_script('Cogent==3.9', 'reconstruct_contig.py')
  File "/home/mpimp-golm.mpg.de/afischer/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/mpimp-golm.mpg.de/afischer/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/home/mpimp-golm.mpg.de/afischer/.conda/envs/anaCogent2/lib/python2.7/site-packages/Cogent-3.9-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 347, in <module>
    main()
  File "/home/mpimp-golm.mpg.de/afischer/.conda/envs/anaCogent2/lib/python2.7/site-packages/Cogent-3.9-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 250, in main
    run_Cogent_on_input()
  File "/home/mpimp-golm.mpg.de/afischer/.conda/envs/anaCogent2/lib/python2.7/site-packages/Cogent-3.9-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 145, in run_Cogent_on_input
    adjusted_kmer = splice_cycle.precycle_kmer_adjustment(cc_settings.KMER_SIZE)
  File "/home/mpimp-golm.mpg.de/afischer/.conda/envs/anaCogent2/lib/python2.7/site-packages/Cogent-3.9-py2.7.egg/Cogent/splice_cycle.py", line 33, in precycle_kmer_adjustment
    kmer_usage[r.seq.tostring()[i:i+kmer_size]][r.id].append(i)
AttributeError: 'Seq' object has no attribute 'tostring'`

With python version 2.7.14 it just informs you that the tostring() method is deprecated:
`/home/mpimp-golm.mpg.de/schaarschmidt/.conda/envs/anaCogent/lib/python2.7/site-packages/Bio/Seq.py:354: BiopythonDeprecationWarning: This method is obsolete; please use str(my_seq) instead of my_seq.tostring().
  BiopythonDeprecationWarning)`

You maybe should keep that in mind for any new Cogent version.

best regards
Axel

**Comment by ckuanglim85** [comment]
How to run reconstruct_contig.py with python 2.7.15 ?

**Comment by Magdoll** [comment]
Hi @ckuanglim85 ,

I don't think the issue is with Python versions. It is likely the BioPython module version difference as you can see the warning comes from BioPython:

```
BiopythonDeprecationWarning: This method is obsolete; please use str(my_seq) instead of my_seq.tostring(). BiopythonDeprecationWarning
```

Cogent is currently tested on v1.7.1

```
>>> import Bio
>>> Bio.__version__
'1.71'
```
