### ISSUE TITLE
Error running collapse_isoforms_by_sam.py

### ISSUE THREAD

**Issue by goodgodric28** [Magdoll/Cogent#65]
I get this error when I try to run collapse_isoforms_by_sam.py on my data:

>merged 1 down to 1 transcripts
merged 1 down to 1 transcripts
merged 1 down to 1 transcripts
merged 1 down to 1 transcripts
alt. junction found at 13
alt. junction found at 1158
alt. junction found at 1677
merged 2 down to 2 transcripts
merged 1 down to 1 transcripts
merged 1 down to 1 transcripts
Traceback (most recent call last):
  File "/home/goodheart/miniconda2/envs/anaCogent/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('cupcake==6.2', 'collapse_isoforms_by_sam.py')
  File "/home/goodheart/miniconda2/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/goodheart/miniconda2/envs/anaCogent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "/home/goodheart/miniconda2/envs/anaCogent/lib/python2.7/site-packages/cupcake-6.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 248, in <module>
    main(args)
  File "/home/goodheart/miniconda2/envs/anaCogent/lib/python2.7/site-packages/cupcake-6.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 207, in main
    collapse_fuzzy_junctions(f_good.name, f_txt.name, args.allow_extra_5exon, internal_fuzzy_max_dist=args.max_fuzzy_junction)
  File "/home/goodheart/miniconda2/envs/anaCogent/lib/python2.7/site-packages/cupcake-6.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 152, in collapse_fuzzy_junctions
    _size = get_fl_from_id(group_info[pbid])
  File "/home/goodheart/miniconda2/envs/anaCogent/lib/python2.7/site-packages/cupcake-6.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 92, in get_fl_from_id
    return sum(int(_id.split('/')[1].split('p')[0][1:]) for _id in members)
  File "/home/goodheart/miniconda2/envs/anaCogent/lib/python2.7/site-packages/cupcake-6.2-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 92, in <genexpr>
    return sum(int(_id.split('/')[1].split('p')[0][1:]) for _id in members)
IndexError: list index out of range

The files that gave me this error are here: ﻿https://www.dropbox.com/s/4tcufga8thcqkh5/4cells.zip?dl=0
While similar files that worked fine for me are here: https://www.dropbox.com/s/ksdt0njjsjgsas5/2cells.zip?dl=0

Any help you can give would be appreciated. Thank you.

**Comment by goodgodric28** [comment]
Turns out this was an issue with needing forward slashes instead of underscores in my headers.
