### ISSUE TITLE
BiopythonDeprecationWarning: This method is obsolete; please use str(my_seq) instead of my_seq.tostring().

### ISSUE THREAD

**Issue by Yali1989** [Magdoll/Cogent#77]
When I run reconstruct_contig.py, I get this issue and error.

2.17-r943-dirty
/home/wangyali/anaconda2/lib/python2.7/site-packages/Bio/Seq.py:341: BiopythonDeprecationWarning: This method is obsolete; please use str(my_seq) instead of my_seq.tostring().
  BiopythonDeprecationWarning)
Traceback (most recent call last):
  File "/home/wangyali/yaliwang/Software/Cogent/build/scripts-2.7/reconstruct_contig.py", line 347, in <module>
    main()
  File "/home/wangyali/yaliwang/Software/Cogent/build/scripts-2.7/reconstruct_contig.py", line 250, in main
    run_Cogent_on_input()
  File "/home/wangyali/yaliwang/Software/Cogent/build/scripts-2.7/reconstruct_contig.py", line 165, in run_Cogent_on_input
    homo_nodes = filter(lambda n: G.has_edge(n, n), G.nodes_iter())
AttributeError: 'DiGraph' object has no attribute 'nodes_iter'

can you fix this script?
Thanks!

**Comment by Magdoll** [comment]
This issue should not exist if using networkx v2.3 and higher and with the latest Cogent v6.0.0 (for Python 3.7). Re-open if needed.
