### ISSUE TITLE
execution error with reconstruct_contig.py FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jcleple33** [Magdoll/Cogent#83]
Running cogent 6.0.0 / reconstruct_contig.py I got such error on several cluster for which reconstruction failed using kmer 30, 60 and 80:

un example below:
jleple@genologin1 /work/jleple/PACBIOII/E656_SMRTCell_A/COGENT_A $ cat slurm-19002922_10.out
2.17-r941
Traceback (most recent call last):
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3-4.4.10/envs/cogent-6.0.0_env/bin/reconstruct_contig.py", line 4, in <module>
    __import__('pkg_resources').run_script('Cogent==6.0.0', 'reconstruct_contig.py')
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3-4.4.10/envs/cogent-6.0.0_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3-4.4.10/envs/cogent-6.0.0_env/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/bioinfo/src/Miniconda/Miniconda3-4.4.10/envs/cogent-6.0.0_env/lib/python3.7/site-packages/Cogent-6.0.0-py3.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 346, in <module>
    os.chdir(args.dirname)
FileNotFoundError: [Errno 2] No such file or directory: 'ccs_A/1982_0'

but ccs_A/1982_0 exists! I do not understand:

jleple@genologin1 /work/jleple/PACBIOII/E656_SMRTCell_A/COGENT_A $ ls ccs_A/1982_0
CYCLE_DETECTED  hello.log  in.fa  in.trimmed.fa  in.weights

Below the command line used to try to reconstruct this files:

reconstruct_contig.py --nx_cycle_detection -k 80 ccs_A/1172_19320"

NB: version of networks is 2.3 as I have an error running process_kmer_to_graph.py with 2.4 (error already reported)

I attached the directory ccsA_/1980_0 as example

Please, could you help me. Thanks in advance!
[ccs_A.zip](https://github.com/Magdoll/Cogent/files/5116282/ccs_A.zip)

**Comment by Magdoll** [comment]
Hi @jcleple33 , I'm looking into this now. Pretty sure it's a minor bug in the code...

**Comment by Magdoll** [comment]
Hi @jcleple33 , I believe I've fixed the issue in v6.1.0. 
the run result is [here](https://www.dropbox.com/s/jl1tmdla5kd4f0w/1982_0.tar.gz?dl=0)

Let me know if this works for you!
-Liz

**Comment by jcleple33** [comment]
Dear Liz,

Yes the issue is fixed. However I obtain other errors for the last 9 clusters. I have tried with k 60, 80  and 120 and I got these messages for each of the clusters 1 to 9 (see error messages slurm-19087499_1.out to slurm-19087499_9.out). should I try to increase k over 120?

1	ccs_A/1172_11533
2	ccs_A/1172_11657
3	ccs_A/1172_9583
4	ccs_A/16661_7
5	ccs_A/282_0
6	ccs_A/30518_0
7	ccs_A/3144_5
8	ccs_A/32104_357
9	ccs_A/32167_0

I attached the last one ccs_A/32167_0 as example

Sincerely

Jean-Charles




jleple@genologin2 /work/jleple/PACBIOII/E656_SMRTCell_A/COGENT_A $ cat slurm-19087499_1.out
2.17-r941
/bin/bash : ligne 1 : 116440 Erreur de segmentation  reconstruct_contig.py --nx_cycle_detection -k 120 ccs_A/1172_11533

jleple@genologin2 /work/jleple/PACBIOII/E656_SMRTCell_A/COGENT_A $ cat slurm-19087499_2.out
2.17-r941
/bin/bash : ligne 1 :  5057 Erreur de segmentation  reconstruct_contig.py --nx_cycle_detection -k 120 ccs_A/1172_11657

jleple@genologin2 /work/jleple/PACBIOII/E656_SMRTCell_A/COGENT_A $ cat slurm-19087499_3.out
2.17-r941
[M::mm_idx_gen::0.008*1.06] collected minimizers
[M::mm_idx_gen::0.016*0.91] sorted minimizers
[M::main::0.016*0.91] loaded/built the index for 20 target sequence(s)
[M::mm_mapopt_update::0.017*0.91] mid_occ = 19
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 20
[M::mm_idx_stat::0.018*0.92] distinct minimizers: 13108 (67.98% are singletons); average occurrences: 2.661; average spacing: 2.931
[M::worker_pipeline::0.268*0.99] mapped 20 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -ax splice -t 1 cogent.fa in.trimmed.fa
[M::main] Real time: 0.270 sec; CPU: 0.268 sec; Peak RSS: 0.007 GB
[M::mm_idx_gen::0.009*1.07] collected minimizers
[M::mm_idx_gen::0.016*1.04] sorted minimizers
[M::main::0.016*1.04] loaded/built the index for 19 target sequence(s)
[M::mm_mapopt_update::0.017*1.04] mid_occ = 16
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 19
[M::mm_idx_stat::0.018*1.04] distinct minimizers: 17268 (80.07% are singletons); average occurrences: 1.885; average spacing: 2.928
[M::worker_pipeline::0.199*1.00] mapped 20 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -ax splice -t 1 cogent.fa in.trimmed.fa
[M::main] Real time: 0.201 sec; CPU: 0.201 sec; Peak RSS: 0.006 GB
[M::mm_idx_gen::0.004*1.12] collected minimizers
[M::mm_idx_gen::0.006*1.07] sorted minimizers
[M::main::0.006*1.07] loaded/built the index for 5 target sequence(s)
[M::mm_mapopt_update::0.007*1.06] mid_occ = 6
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 5
[M::mm_idx_stat::0.007*1.06] distinct minimizers: 5681 (81.89% are singletons); average occurrences: 1.374; average spacing: 2.905
[M::worker_pipeline::0.034*1.01] mapped 5 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -ax splice -t 1 cogent.fa in.trimmed.fa
[M::main] Real time: 0.036 sec; CPU: 0.035 sec; Peak RSS: 0.005 GB
/bin/bash : ligne 1 : 39105 Erreur de segmentation  reconstruct_contig.py --nx_cycle_detection -k 120 ccs_A/1172_9583


jleple@genologin2 /work/jleple/PACBIOII/E656_SMRTCell_A/COGENT_A $ cat slurm-19087499_4.out
2.17-r941
CYCLE detected through simple_cycles! Raise CycleDetectedException!
CYCLE detected through simple_cycles! Raise CycleDetectedException!
CYCLE detected through simple_cycles! Raise CycleDetectedException!
CYCLE detected through simple_cycles! Raise CycleDetectedException!


jleple@genologin2 /work/jleple/PACBIOII/E656_SMRTCell_A/COGENT_A $ cat slurm-19087499_5.out
2.17-r941
/bin/bash : ligne 1 : 170766 Erreur de segmentation  reconstruct_contig.py --nx_cycle_detection -k 120 ccs_A/282_0
jleple@genologin2 /work/jleple/PACBIOII/E656_SMRTCell_A/COGENT_A $ cat slurm-19087499_6.out
2.17-r941
skipping split_0 because done already
skipping split_1 because done already
skipping split_2 because done already
skipping split_3 because done already
skipping split_4 because done already
skipping split_5 because done already
skipping split_6 because done already
skipping split_7 because done already
skipping split_8 because done already
CYCLE detected through simple_cycles! Raise CycleDetectedException!
skipping split_0 because done already
skipping split_1 because done already
skipping split_2 because done already
skipping split_3 because done already
skipping split_4 because done already
skipping split_5 because done already
skipping split_6 because done already
skipping split_7 because done already
skipping split_8 because done already
skipping split_0 because done already
skipping split_1 because done already
skipping split_2 because done already
skipping split_3 because done already
skipping split_4 because done already
skipping split_5 because done already
skipping split_6 because done already
skipping split_7 because done already
skipping split_8 because done already
CYCLE detected through simple_cycles! Raise CycleDetectedException!
skipping split_0 because done already
skipping split_1 because done already
skipping split_2 because done already
skipping split_3 because done already
skipping split_4 because done already
skipping split_5 because done already
skipping split_6 because done already
skipping split_7 because done already
skipping split_8 because done already
CYCLE detected through simple_cycles! Raise CycleDetectedException!
skipping split_0 because done already
skipping split_1 because done already
skipping split_2 because done already
skipping split_3 because done already
skipping split_4 because done already
skipping split_5 because done already
skipping split_6 because done already
skipping split_7 because done already
skipping split_8 because done already
CYCLE detected through simple_cycles! Raise CycleDetectedException!


jleple@genologin2 /work/jleple/PACBIOII/E656_SMRTCell_A/COGENT_A $ cat slurm-19087499_7.out
2.17-r941
CYCLE detected through simple_cycles! Raise CycleDetectedException!
CYCLE detected through simple_cycles! Raise CycleDetectedException!


jleple@genologin2 /work/jleple/PACBIOII/E656_SMRTCell_A/COGENT_A $ cat slurm-19087499_8.out
2.17-r941
/bin/bash : ligne 1 : 102490 Erreur de segmentation  reconstruct_contig.py --nx_cycle_detection -k 120 ccs_A/32104_357


jleple@genologin2 /work/jleple/PACBIOII/E656_SMRTCell_A/COGENT_A $ cat slurm-19087499_9.out
2.17-r941
/bin/bash : ligne 1 : 137602 Erreur de segmentation  reconstruct_contig.py --nx_cycle_detection -k 120 ccs_A/32167_0



[32167_0.zip](https://github.com/Magdoll/Cogent/files/5150162/32167_0.zip)

**Comment by Magdoll** [comment]
Hi @jcleple33 ,
interesting I am able to run 32167_0 with just `reconstruct_contigs.py 32167_0/`...no issue found...!

The result is here: https://www.dropbox.com/s/divzx2l62gtzxva/32167_0.tar.gz?dl=0
