### ISSUE TITLE
Error in reconstruct_contig.py

### ISSUE THREAD

**Issue by wonitawowowo** [Magdoll/Cogent#96]
Hellow,during I running Cogent with the test data as described by WIKI,one error rise:
reconstruct_contig.py test_human/test_human_0
Then I got:
--------------------------------------------------------------------------------------------------------------------------------------------
2.15-r905
/home/kangzong/miniconda3/envs/anaCogent/lib/python3.7/site-packages/pulp/pulp.py:1316: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")
GLPSOL: GLPK LP/MIP Solver, v4.57
Parameter(s) specified in the command line:
 --cpxlp /tmp/68855a6aa81a490c82ca65ce971a891e-pulp.lp -o /tmp/68855a6aa81a490c82ca65ce971a891e-pulp.sol
Reading problem data from '/tmp/68855a6aa81a490c82ca65ce971a891e-pulp.lp'...
/tmp/68855a6aa81a490c82ca65ce971a891e-pulp.lp:3: missing variable name
CPLEX LP file processing error
GLPSOL: GLPK LP/MIP Solver, v4.57
Parameter(s) specified in the command line:
 --cpxlp /tmp/248b1b97686c4ac5827d5cbef0a84af5-pulp.lp -o /tmp/248b1b97686c4ac5827d5cbef0a84af5-pulp.sol
Reading problem data from '/tmp/248b1b97686c4ac5827d5cbef0a84af5-pulp.lp'...
/tmp/248b1b97686c4ac5827d5cbef0a84af5-pulp.lp:3: missing variable name
CPLEX LP file processing error
Traceback (most recent call last):
  File "/home/kangzong/miniconda3/envs/anaCogent/lib/python3.7/site-packages/Cogent-8.0.0-py3.7.egg/Cogent/process_path.py", line 132, in solve_with_lp_and_reduce
    prob.solve()
  File "/home/kangzong/miniconda3/envs/anaCogent/lib/python3.7/site-packages/pulp/pulp.py", line 1880, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/home/kangzong/miniconda3/envs/anaCogent/lib/python3.7/site-packages/pulp/apis/glpk_api.py", line 115, in actualSolve
    raise PulpSolverError("PuLP: Error while executing " + self.path)
pulp.apis.core.PulpSolverError: PuLP: Error while executing glpsol

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kangzong/miniconda3/envs/anaCogent/bin/reconstruct_contig.py", line 4, in <module>
    __import__('pkg_resources').run_script('Cogent==8.0.0', 'reconstruct_contig.py')
  File "/home/kangzong/miniconda3/envs/anaCogent/lib/python3.7/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/kangzong/miniconda3/envs/anaCogent/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/home/kangzong/miniconda3/envs/anaCogent/lib/python3.7/site-packages/Cogent-8.0.0-py3.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 358, in <module>
    main()
  File "/home/kangzong/miniconda3/envs/anaCogent/lib/python3.7/site-packages/Cogent-8.0.0-py3.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 254, in main
    run_Cogent_on_input()
  File "/home/kangzong/miniconda3/envs/anaCogent/lib/python3.7/site-packages/Cogent-8.0.0-py3.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 229, in run_Cogent_on_input
    solve_with_lp_and_reduce(good_for, paths, mermap)
  File "/home/kangzong/miniconda3/envs/anaCogent/lib/python3.7/site-packages/Cogent-8.0.0-py3.7.egg/Cogent/process_path.py", line 135, in solve_with_lp_and_reduce
    prob.solve()
  File "/home/kangzong/miniconda3/envs/anaCogent/lib/python3.7/site-packages/pulp/pulp.py", line 1880, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/home/kangzong/miniconda3/envs/anaCogent/lib/python3.7/site-packages/pulp/apis/glpk_api.py", line 115, in actualSolve
    raise PulpSolverError("PuLP: Error while executing " + self.path)
pulp.apis.core.PulpSolverError: PuLP: Error while executing glpsol
----------------------------------------------------------------------------------------------------------------------------------------------
I saw #95 solved it by updated PuLP,but my PuLP's version is 2.5.0,I don't know how to solve it.Could you help me?
By the way ,when I install Cogent as wiki said:
conda install -n anaCogent -c bcbio bx-python
conda told me the bx-python0.7.3 is for python2.7,so I do:
conda install -n anaCogent -c conda-forge bx-python to install 0.8.11
Could this lead to the problem?

**Comment by Magdoll** [comment]
Hi @wonitawowowo ,
I checked my pulp version and it's 1.6.8. I'm not sure if having a newer version (2.5.0 as you do) is the problem? One possible way is to downgrade pulp to 1.6.8 and see if that works..
-Liz

**Comment by wonitawowowo** [comment]
Thanks @Magdoll I will try it.
